# Generated by Django 5.1.4 on 2025-01-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_neccessity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='neccessity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('food', 'FOOD'), ('drink', 'DRINK'), ('snacks', 'SNACKS'), ('cleaning supplies', 'CLEANING SUPPLIES'), ('others', 'OTHERS')], default='others', max_length=50),
        ),
    ]
